use crate::element_trait::ElementDef;
use aura_lite_core::element_id::*;
use aura_lite_utils::color::Rgba;
use std::sync::OnceLock;

// Full registry of elements
#[allow(clippy::too_many_arguments)]
fn def(
    id: u16,
    name: &'static str,
    color: Rgba,
    density: f32,
    temp: u16,
    half_life: u64,
    fissile: bool,
    moderator: bool,
    radiation: bool,
    pen: u32,
) -> ElementDef {
    ElementDef {
        id,
        name,
        color,
        density,
        temperature: temp,
        half_life_ticks: half_life,
        is_fissile: fissile,
        is_moderator: moderator,
        is_radiation: radiation,
        penetration: pen,
    }
}

pub fn all_definitions() -> Vec<ElementDef> {
    vec![
        def(
            AIR,
            "Air",
            Rgba::new(0, 0, 0, 0),
            0.0,
            293,
            0,
            false,
            false,
            false,
            0,
        ),
        def(
            SAND,
            "Sand",
            Rgba::rgb(194, 178, 128),
            2.5,
            293,
            0,
            false,
            false,
            false,
            0,
        ),
        def(
            WATER,
            "Water",
            Rgba::rgb(64, 164, 223),
            1.0,
            293,
            0,
            false,
            true,
            false,
            0,
        ),
        def(
            STONE,
            "Stone",
            Rgba::rgb(120, 120, 120),
            3.0,
            293,
            0,
            false,
            false,
            false,
            0,
        ),
        def(
            U235,
            "Uranium-235",
            Rgba::rgb(80, 200, 60),
            19.1,
            293,
            1_000_000,
            true,
            false,
            false,
            0,
        ),
        def(
            U238,
            "Uranium-238",
            Rgba::rgb(70, 170, 50),
            19.1,
            293,
            2_000_000,
            true,
            false,
            false,
            0,
        ),
        def(
            PU239,
            "Plutonium-239",
            Rgba::rgb(200, 60, 60),
            19.8,
            293,
            500_000,
            true,
            false,
            false,
            0,
        ),
        def(
            PU240,
            "Plutonium-240",
            Rgba::rgb(180, 40, 40),
            19.8,
            293,
            400_000,
            true,
            false,
            false,
            0,
        ),
        def(
            HEAVY_WATER,
            "Heavy Water",
            Rgba::rgb(80, 180, 230),
            1.1,
            293,
            0,
            false,
            true,
            false,
            0,
        ),
        def(
            GRAPHITE,
            "Graphite",
            Rgba::rgb(50, 50, 50),
            2.2,
            293,
            0,
            false,
            true,
            false,
            0,
        ),
        def(
            LEAD,
            "Lead",
            Rgba::rgb(90, 90, 100),
            11.3,
            293,
            0,
            false,
            false,
            false,
            0,
        ),
        def(
            CONCRETE,
            "Concrete",
            Rgba::rgb(160, 160, 155),
            2.8,
            293,
            0,
            false,
            false,
            false,
            0,
        ),
        def(
            STEEL,
            "Steel",
            Rgba::rgb(170, 170, 180),
            7.8,
            293,
            0,
            false,
            false,
            false,
            0,
        ),
        def(
            NEUTRON_THERMAL,
            "Thermal Neutron",
            Rgba::rgb(255, 255, 150),
            0.001,
            350,
            0,
            false,
            false,
            true,
            8,
        ),
        def(
            NEUTRON_FAST,
            "Fast Neutron",
            Rgba::rgb(255, 80, 80),
            0.001,
            800,
            0,
            false,
            false,
            true,
            15,
        ),
        def(
            GAMMA,
            "Gamma Ray",
            Rgba::rgb(255, 255, 0),
            0.0,
            1000,
            0,
            false,
            false,
            true,
            12,
        ),
        def(
            ALPHA,
            "Alpha",
            Rgba::rgb(255, 120, 0),
            0.01,
            400,
            0,
            false,
            false,
            true,
            2,
        ),
        def(
            BETA,
            "Beta",
            Rgba::rgb(80, 200, 255),
            0.005,
            400,
            0,
            false,
            false,
            true,
            4,
        ),
        def(
            DEPLETED_URANIUM,
            "Depleted Uranium",
            Rgba::rgb(60, 120, 40),
            19.1,
            293,
            0,
            false,
            false,
            false,
            0,
        ),
        def(
            FISSION_PRODUCTS,
            "Fission Products",
            Rgba::rgb(100, 180, 40),
            5.0,
            600,
            0,
            false,
            false,
            false,
            0,
        ),
        def(
            TRITIUM,
            "Tritium",
            Rgba::new(150, 200, 255, 200),
            0.8,
            293,
            100_000,
            false,
            false,
            false,
            0,
        ),
        def(
            DEUTERIUM,
            "Deuterium",
            Rgba::new(120, 220, 255, 200),
            0.8,
            293,
            0,
            false,
            false,
            false,
            0,
        ),
        def(
            TNT,
            "TNT",
            Rgba::rgb(220, 50, 50),
            1.6,
            293,
            0,
            false,
            false,
            false,
            0,
        ),
        def(
            HYDROGEN,
            "Hydrogen",
            Rgba::new(200, 230, 255, 200),
            0.07,
            293,
            0,
            false,
            false,
            false,
            0,
        ),
        def(
            LITHIUM,
            "Lithium",
            Rgba::rgb(200, 200, 200),
            0.5,
            293,
            0,
            false,
            false,
            false,
            0,
        ),
        def(
            HELIUM,
            "Helium",
            Rgba::new(255, 254, 200, 200),
            0.1,
            293,
            0,
            false,
            false,
            false,
            0,
        ),
        def(
            MOLTEN_FUEL,
            "Molten Fuel",
            Rgba::rgb(255, 100, 0),
            10.0,
            2500,
            0,
            true,
            false,
            false,
            0,
        ),
        def(
            FALLOUT,
            "Fallout",
            Rgba::rgb(80, 80, 30),
            2.0,
            400,
            0,
            false,
            false,
            false,
            0,
        ),
        def(
            BORON,
            "Boron",
            Rgba::rgb(100, 90, 80),
            2.3,
            293,
            0,
            false,
            false,
            false,
            0,
        ),
        def(
            STEAM,
            "Steam",
            Rgba::new(220, 220, 230, 180),
            0.05,
            400,
            0,
            false,
            false,
            false,
            0,
        ),
        def(
            ICE,
            "Ice",
            Rgba::rgb(180, 220, 255),
            0.92,
            260,
            0,
            false,
            false,
            false,
            0,
        ),
        def(XENON, "Xenon", Rgba::rgb(180, 140, 220), 0.06, 300, 8_000, false, false, false, 0),
        def(FIRE, "Fire", Rgba::rgb(255, 90, 20), 0.02, 1100, 0, false, false, false, 0),
        def(WOOD, "Wood", Rgba::rgb(140, 90, 40), 0.7, 293, 0, false, false, false, 0),
        def(ACID, "Acid", Rgba::rgb(80, 220, 40), 1.2, 293, 0, false, false, false, 0),
        def(WIRE, "Wire", Rgba::rgb(200, 160, 40), 8.0, 293, 0, false, false, false, 0),
        def(HEATER, "Heater", Rgba::rgb(180, 40, 40), 7.5, 800, 0, false, false, false, 0),
        def(PUMP, "Pump", Rgba::rgb(60, 80, 160), 6.0, 293, 0, false, false, false, 0),
        def(PIPE, "Pipe", Rgba::rgb(90, 100, 110), 5.5, 293, 0, false, false, false, 0),
        def(SENSOR, "Sensor", Rgba::rgb(40, 200, 180), 4.0, 293, 0, false, false, false, 0),
        def(CONTROL_ROD, "Control Rod", Rgba::rgb(70, 70, 90), 2.5, 293, 0, false, false, false, 0),
        def(SLAG, "Slag", Rgba::rgb(90, 70, 50), 3.2, 400, 0, false, false, false, 0),
        def(COAL, "Coal", Rgba::rgb(30, 30, 30), 1.3, 293, 0, false, false, false, 0),
        def(SPARK, "Spark", Rgba::rgb(255, 255, 180), 0.001, 900, 0, false, false, true, 1),
        def(FILTER, "Filter", Rgba::rgb(160, 190, 170), 4.5, 293, 0, false, false, false, 0),
        def(IODINE, "Iodine", Rgba::rgb(160, 90, 200), 0.05, 320, 2_400, false, false, false, 0),
        def(PIPE_WATER, "Pipe (water)", Rgba::rgb(50, 130, 180), 5.6, 300, 0, false, true, false, 0),
        def(PIPE_STEAM, "Pipe (steam)", Rgba::rgb(170, 190, 200), 5.4, 400, 0, false, false, false, 0),
    ]
}

fn by_id() -> &'static [Option<ElementDef>] {
    static BY_ID: OnceLock<Vec<Option<ElementDef>>> = OnceLock::new();
    BY_ID.get_or_init(|| {
        let mut slots: Vec<Option<ElementDef>> = vec![None; (MAX_ELEMENT_ID as usize) + 1];
        for def in all_definitions() {
            let idx = def.id as usize;
            if idx < slots.len() {
                slots[idx] = Some(def);
            }
        }
        slots
    })
}

pub fn definition_ref(id: u16) -> Option<&'static ElementDef> {
    by_id().get(id as usize).and_then(|d| d.as_ref())
}

pub fn get_definition(id: u16) -> Option<ElementDef> {
    definition_ref(id).cloned()
}

pub fn color_for_id(id: u16) -> [u8; 4] {
    if let Some(def) = definition_ref(id) {
        [def.color.r, def.color.g, def.color.b, def.color.a]
    } else {
        [255, 0, 255, 255]
    }
}

pub fn name_for_id(id: u16) -> &'static str {
    match id {
        AIR => "Air",
        SAND => "Sand",
        WATER => "Water",
        STONE => "Stone",
        U235 => "Uranium-235",
        U238 => "Uranium-238",
        PU239 => "Plutonium-239",
        PU240 => "Plutonium-240",
        HEAVY_WATER => "Heavy Water",
        GRAPHITE => "Graphite",
        LEAD => "Lead",
        CONCRETE => "Concrete",
        STEEL => "Steel",
        NEUTRON_THERMAL => "Thermal Neutron",
        NEUTRON_FAST => "Fast Neutron",
        GAMMA => "Gamma Ray",
        ALPHA => "Alpha",
        BETA => "Beta",
        DEPLETED_URANIUM => "Depleted Uranium",
        FISSION_PRODUCTS => "Fission Products",
        TRITIUM => "Tritium",
        DEUTERIUM => "Deuterium",
        TNT => "TNT",
        HYDROGEN => "Hydrogen",
        LITHIUM => "Lithium",
        HELIUM => "Helium",
        MOLTEN_FUEL => "Molten Fuel",
        FALLOUT => "Fallout",
        BORON => "Boron",
        STEAM => "Steam",
        ICE => "Ice",
        XENON => "Xenon",
        FIRE => "Fire",
        WOOD => "Wood",
        ACID => "Acid",
        WIRE => "Wire",
        HEATER => "Heater",
        PUMP => "Pump",
        PIPE => "Pipe",
        SENSOR => "Sensor",
        CONTROL_ROD => "Control Rod",
        SLAG => "Slag",
        COAL => "Coal",
        SPARK => "Spark",
        FILTER => "Filter",
        IODINE => "Iodine",
        PIPE_WATER => "Pipe (water)",
        PIPE_STEAM => "Pipe (steam)",
        _ => "Unknown",
    }
}

pub fn density_for_id(id: u16) -> f32 {
    aura_lite_core::element_id::density_for_id(id)
}
